### ISSUE TITLE
Install error (README.PyPI.md not found)

### ISSUE THREAD

**Issue by yuki-koyama** [yuki-koyama/visoptslider#5]
With pip 18.1, the following error occurred

```
pip3 install visoptslider
```
```
  Downloading https://files.pythonhosted.org/packages/00/7a/648eee0ea51ec477238d9e722641f1e87f990bcc9ecaa55604eca3c8c58d/visoptslider-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/yf/cjjz3kzs17n2b072bltd8lfr0000gn/T/pip-install-p53ht40i/visoptslider/setup.py", line 3, in <module>
        with open("README.PyPI.md", "r") as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.PyPI.md'
```
It seems that the distributed tar.gz does not include `README.PyPI.md`, which should be included.

**Comment by yuki-koyama** [comment]
This commit 524607d8f71659324683681b632289897ccd0948 fixed this issue
